"""changed name to first and last name

Revision ID: 0cbfc59d7f99
Revises: 87b3a970ddf0
Create Date: 2023-02-18 13:13:08.716235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbfc59d7f99'
down_revision = '87b3a970ddf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('fistName', sa.String(), nullable=True))
    op.add_column('author', sa.Column('lastName', sa.String(), nullable=True))
    op.drop_column('author', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('author', 'lastName')
    op.drop_column('author', 'fistName')
    # ### end Alembic commands ###
