"""nothing

Revision ID: 16de88003c84
Revises: b89b52364ded
Create Date: 2023-02-18 12:56:54.987154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16de88003c84'
down_revision = 'b89b52364ded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
