"""a

Revision ID: 769efd3b2f07
Revises: 55ea7d8d66b0
Create Date: 2023-03-19 20:00:00.105491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769efd3b2f07'
down_revision = '55ea7d8d66b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
