"""knowledge spaces

Revision ID: 04ed713e870d
Revises: 8a1a85a60638
Create Date: 2023-03-23 21:50:19.590183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ed713e870d'
down_revision = '8a1a85a60638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_relations',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['concept.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_space_id'], ['knowledge_space.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['concept.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'destination_id', 'knowledge_space_id')
    )
    op.drop_constraint('answer_question_id_fkey', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('concept_profession_id_fkey', 'concept', type_='foreignkey')
    op.create_foreign_key(None, 'concept', 'profession', ['profession_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint('learned_concepts_student_id_fkey', 'learned_concepts', type_='foreignkey')
    op.drop_constraint('learned_concepts_concept_id_fkey', 'learned_concepts', type_='foreignkey')
    op.create_foreign_key(None, 'learned_concepts', 'user', ['student_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'learned_concepts', 'concept', ['concept_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('question_test_id_fkey', 'question', type_='foreignkey')
    op.drop_constraint('question_concept_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'concept', ['concept_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(None, 'question', 'test', ['test_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('submitted_answers_answer_id_fkey', 'submitted_answers', type_='foreignkey')
    op.drop_constraint('submitted_answers_test_id_student_id_fkey', 'submitted_answers', type_='foreignkey')
    op.create_foreign_key(None, 'submitted_answers', 'test_submissions', ['test_id', 'student_id'], ['test_id', 'student_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'submitted_answers', 'answer', ['answer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('test_creator_id_fkey', 'test', type_='foreignkey')
    op.create_foreign_key(None, 'test', 'user', ['creator_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('test_submissions_student_id_fkey', 'test_submissions', type_='foreignkey')
    op.drop_constraint('test_submissions_test_id_fkey', 'test_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'test_submissions', 'user', ['student_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'test_submissions', 'test', ['test_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'user', ['user_id'], ['id'])
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'test_submissions', type_='foreignkey')
    op.drop_constraint(None, 'test_submissions', type_='foreignkey')
    op.create_foreign_key('test_submissions_test_id_fkey', 'test_submissions', 'test', ['test_id'], ['id'])
    op.create_foreign_key('test_submissions_student_id_fkey', 'test_submissions', 'user', ['student_id'], ['id'])
    op.drop_constraint(None, 'test', type_='foreignkey')
    op.create_foreign_key('test_creator_id_fkey', 'test', 'user', ['creator_id'], ['id'])
    op.drop_constraint(None, 'submitted_answers', type_='foreignkey')
    op.drop_constraint(None, 'submitted_answers', type_='foreignkey')
    op.create_foreign_key('submitted_answers_test_id_student_id_fkey', 'submitted_answers', 'test_submissions', ['test_id', 'student_id'], ['test_id', 'student_id'])
    op.create_foreign_key('submitted_answers_answer_id_fkey', 'submitted_answers', 'answer', ['answer_id'], ['id'])
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_concept_id_fkey', 'question', 'concept', ['concept_id'], ['id'])
    op.create_foreign_key('question_test_id_fkey', 'question', 'test', ['test_id'], ['id'])
    op.drop_constraint(None, 'learned_concepts', type_='foreignkey')
    op.drop_constraint(None, 'learned_concepts', type_='foreignkey')
    op.create_foreign_key('learned_concepts_concept_id_fkey', 'learned_concepts', 'concept', ['concept_id'], ['id'])
    op.create_foreign_key('learned_concepts_student_id_fkey', 'learned_concepts', 'user', ['student_id'], ['id'])
    op.drop_constraint(None, 'concept', type_='foreignkey')
    op.create_foreign_key('concept_profession_id_fkey', 'concept', 'profession', ['profession_id'], ['id'])
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_question_id_fkey', 'answer', 'question', ['question_id'], ['id'])
    op.drop_table('concept_relations')
    op.drop_table('knowledge_space')
    # ### end Alembic commands ###
