"""update user model

Revision ID: ba02d42472fe
Revises: 2ce7e902dae8
Create Date: 2023-03-19 19:20:02.674179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba02d42472fe'
down_revision = '2ce7e902dae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
