"""trying

Revision ID: 98cbb7da3363
Revises: 3cd89e657e62
Create Date: 2023-03-01 20:48:40.707656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cbb7da3363'
down_revision = '3cd89e657e62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
