"""test publication

Revision ID: 5b7ac4fc671c
Revises: 04ed713e870d
Create Date: 2023-03-23 22:10:15.510984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7ac4fc671c'
down_revision = '04ed713e870d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_publication',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_space_id'], ['knowledge_space.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', 'knowledge_space_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_publication')
    # ### end Alembic commands ###
