"""update user model

Revision ID: 054902a716a9
Revises: 28e41d275ad4
Create Date: 2023-03-19 19:13:00.300031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054902a716a9'
down_revision = '28e41d275ad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
