"""question and answer combination

Revision ID: 658566dc16a2
Revises: 5a552a57613e
Create Date: 2023-03-20 12:37:50.227752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658566dc16a2'
down_revision = '5a552a57613e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
