"""test submissions with answers

Revision ID: 635be6e7b253
Revises: 
Create Date: 2023-03-21 09:39:41.980311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635be6e7b253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_submissions',
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('test_id', 'student_id')
    )
    op.create_table('submitted_answers',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['test_submissions.student_id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test_submissions.test_id'], ),
    sa.PrimaryKeyConstraint('test_id', 'student_id', 'answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitted_answers')
    op.drop_table('test_submissions')
    # ### end Alembic commands ###
