"""New Migration

Revision ID: 21141bb37694
Revises: e3977a8aa5b3
Create Date: 2023-02-17 22:45:33.157661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21141bb37694'
down_revision = 'e3977a8aa5b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('nesto', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'nesto')
    # ### end Alembic commands ###
