"""New Migration

Revision ID: 4c88f58f16a6
Revises: 21141bb37694
Create Date: 2023-02-17 22:49:25.354102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c88f58f16a6'
down_revision = '21141bb37694'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
