"""nothing

Revision ID: 5c5c2d91224c
Revises: 16de88003c84
Create Date: 2023-02-18 13:03:52.277726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5c5c2d91224c'
down_revision = '16de88003c84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = postgresql.ENUM('male', 'female', name='gender_enum')
    gender_enum.create(op.get_bind())

    op.add_column('author', sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'gender')
    # ### end Alembic commands ###
