"""refactor for startup

Revision ID: 69bd98b7174a
Revises: ee76b2abb1c7
Create Date: 2023-02-21 13:29:41.678989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bd98b7174a'
down_revision = 'ee76b2abb1c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'author', ['password'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='unique')
    op.drop_column('author', 'password')
    # ### end Alembic commands ###
