"""New Migration

Revision ID: 7b95a322d9d4
Revises: f5458e5d1db4
Create Date: 2023-02-18 12:22:46.469970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b95a322d9d4'
down_revision = 'f5458e5d1db4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('gender', sa.String(), nullable=False))
    op.drop_column('author', 'nesto')
    op.add_column('book', sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'gender')
    op.add_column('author', sa.Column('nesto', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('author', 'gender')
    # ### end Alembic commands ###
