"""New Migration

Revision ID: 7ecfb451791d
Revises: 6e16dea3ab3d
Create Date: 2023-02-17 22:56:49.044771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecfb451791d'
down_revision = '6e16dea3ab3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'nesto',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('author_name_key', 'author', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('author_name_key', 'author', ['name'])
    op.alter_column('author', 'nesto',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
