"""spelling change

Revision ID: 84523adb75ea
Revises: 0cbfc59d7f99
Create Date: 2023-02-18 13:36:50.273497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84523adb75ea'
down_revision = '0cbfc59d7f99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('firstName', sa.String(), nullable=True))
    op.drop_column('author', 'fistName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('fistName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('author', 'firstName')
    # ### end Alembic commands ###
