"""add gender enum

Revision ID: 87b3a970ddf0
Revises: 5c5c2d91224c
Create Date: 2023-02-18 13:08:43.760060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '87b3a970ddf0'
down_revision = '5c5c2d91224c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = postgresql.ENUM('male', 'female', name='gender_enum')
    gender_enum.create(op.get_bind())

    op.add_column('author', sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=True))
# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'gender')
    # ### end Alembic commands ###
