"""New Migration

Revision ID: bfb409a9e288
Revises: 77407819e997
Create Date: 2023-02-18 12:38:20.605033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb409a9e288'
down_revision = '77407819e997'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=True))
    op.drop_column('author', 'nesto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('nesto', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('author', 'gender')
    # ### end Alembic commands ###
