"""New Migration

Revision ID: f5458e5d1db4
Revises: 7ecfb451791d
Create Date: 2023-02-17 22:57:30.493213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5458e5d1db4'
down_revision = '7ecfb451791d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
